### ISSUE TITLE
depancy issue php7.0

### ISSUE THREAD

**Issue by j00fek** [niel/php-yenc#7]
fresh ubuntu 16 installed, php7.0 installed for nzedb indexer.

sudo dpkg -i php7.0-yenc_1.3.0_amd64.deb
Selecting previously unselected package php7.0-yenc.
(Reading database ... 171689 files and directories currently installed.)
Preparing to unpack php7.0-yenc_1.3.0_amd64.deb ...
Unpacking php7.0-yenc (1.3.0) ...
dpkg: dependency problems prevent configuration of php7.0-yenc:
 php7.0-yenc depends on php7.0; however:
  Package php7.0 is not installed.

dpkg: error processing package php7.0-yenc (--install):
 dependency problems - leaving unconfigured
Processing triggers for php7.0-cli (7.0.22-0ubuntu0.16.04.1) ...
Errors were encountered while processing:
 php7.0-yenc

root@b0x:~# php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by niel** [comment]
Check which version of PHP 7 you installed, there are actually two version and if you don't use the php7.0-* versions it will fail with that error.
`sudo apt-get install php-pear php7.0 php7.0-cli php7.0-curl php7.0-dev php7.0-common php7.0-gd php7.0-json php7.0-mbstring php-imagick php-mysql php-xml`

**Comment by j00fek** [comment]
that fixed it

thanks for all your work on this!
